name: Compile Secret Contract

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile WASM
        run: |
          rustup target add wasm32-unknown-unknown
          RUSTFLAGS="-C link-arg=-s" cargo build --release --target wasm32-unknown-unknown

      - name: Upload compiled WASM artifact
        uses: actions/upload-artifact@v4
        with:
          name: secret_lockbox_wasm
          path: target/wasm32-unknown-unknown/release/secret_lockbox.wasm
