name: Compile Secret Contract

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Secret Contract Optimizer
        run: |
          docker run --rm -v "$(pwd)":/code \
            --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
            --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
            enigmampc/secret-contract-optimizer:1.0.8

      - name: Upload compiled WASM artifact
        uses: actions/upload-artifact@v4
        with:
          name: secret_lockbox_wasm
          path: artifacts/secret_lockbox.wasm
